### ISSUE TITLE
Fase 7: Procesos Área de Inclusión   (Implementador)

### ISSUE THREAD

**Issue by osvelvargas** [osvelvargas/dsielab_ico#1]
- Liberar CRUD Tipos   de Apoyo
- Liberar CRUD   Información Básica
- Liberar CRUD   Secciones
- Liberar CRUD Items y   tipos de ítems (Observaciones)

**Comment by osvelvargas** [comment]
- Tipo de apoyo no me deja adicionar mas q uno es decir no se ponen en la lista cuando lo adiciones
- Verificar que no se peuden añadir campos con los nombres repetidos.

**Comment by faverhofff** [comment]
Solved.
