### ISSUE TITLE
Error al actualizar colaborador

### ISSUE THREAD

**Issue by osvelvargas** [osvelvargas/dsielab_ico#22]
Al actualizar un colaborador da error con el campo fechaEvaluacion de la tabla colaborador_evaluacion_medica que en base de datos aparece requerido. Validar que al registrar datos del tab correspondiente ese campo sea requerido.

![imagen](https://user-images.githubusercontent.com/20850759/48519696-d0e23400-e83b-11e8-886f-c1613a6b88ab.png)

**Comment by albertofonsecaq** [comment]
La fecha que se usa para actualizar la evaluacion medica es la misma fecha de ingreso del colaborador que puede ser null en la tabla de colaboradores, es decir, que la misma fecha puede ser null en la tabla colaboradores y no null en la tabla colaborador evaluacion medica, ese es el problema.

**Comment by osvelvargas** [comment]
Cuál sería la solución?
